Neos:
  Fusion:
    defaultContext:
      crql: 'Sitegeist\CriQuel\Query::create'

Sitegeist:
  CriQuel:
    operations:
      # chainable Processor operations
      first: 'Sitegeist\CriQuel\Processor\FirstProcessor'
      last: 'Sitegeist\CriQuel\Processor\LastProcessor'
      add: 'Sitegeist\CriQuel\Processor\AddProcessor'
      remove: 'Sitegeist\CriQuel\Processor\RemoveProcessor'
      unique: 'Sitegeist\CriQuel\Processor\UniqueProcessor'
      children: 'Sitegeist\CriQuel\Processor\ChildrenProcessor'
      closest: 'Sitegeist\CriQuel\Processor\ClosestProcessor'
      tethered: 'Sitegeist\CriQuel\Processor\TetheredProcessor'
      filter: 'Sitegeist\CriQuel\Processor\FilterProcessor'
      parent: 'Sitegeist\CriQuel\Processor\ParentProcessor'
      ancestors: 'Sitegeist\CriQuel\Processor\AncestorsProcessor'
      descendants: 'Sitegeist\CriQuel\Processor\DescendantsProcessor'
      withAncestors: 'Sitegeist\CriQuel\Processor\WithAncestorsProcessor'
      withDescendants: 'Sitegeist\CriQuel\Processor\WithDescendantsProcessor'
      referencingNodes:  'Sitegeist\CriQuel\Processor\ReferencingNodesProcessor'
      referencedByNodes:  'Sitegeist\CriQuel\Processor\ReferencedByNodesProcessor'

      # final Extractor operations
      getNodes: 'Sitegeist\CriQuel\Extractor\GetNodesExtractor'
      getNode: 'Sitegeist\CriQuel\Extractor\GetNodeExtractor'
      getReferences: 'Sitegeist\CriQuel\Extractor\GetReferencesExtractor'
      getReference: 'Sitegeist\CriQuel\Extractor\GetReferenceExtractor'
      getProperties: 'Sitegeist\CriQuel\Extractor\GetPropertiesExtractor'
      getProperty: 'Sitegeist\CriQuel\Extractor\GetPropertyExtractor'
      getCount: 'Sitegeist\CriQuel\Extractor\GetCountExtractor'
