Neos:
  Fusion:
    defaultContext:
      crql: 'Sitegeist\CriQuel\Query::create'

Sitegeist:
  CriQuel:
    operations:
      add: 'Sitegeist\CriQuel\Operations\Add'
      remove: 'Sitegeist\CriQuel\Operations\Remove'
      unique: 'Sitegeist\CriQuel\Operations\Unique'
      children: 'Sitegeist\CriQuel\Operations\Children'
      ancestors: 'Sitegeist\CriQuel\Operations\Ancestors'
      descendants: 'Sitegeist\CriQuel\Operations\Descendants'
      withAncestors: 'Sitegeist\CriQuel\Operations\WithAncestors'
      withDescendants: 'Sitegeist\CriQuel\Operations\WithDescendants'
