Neos:
  Fusion:
    defaultContext:
      crql: 'Sitegeist\CriQuel\Query::create'

Sitegeist:
  CriQuel:
    operations:
      # chainable Processor operations
      first: 'Sitegeist\CriQuel\Processor\First'
      last: 'Sitegeist\CriQuel\Processor\Last'
      add: 'Sitegeist\CriQuel\Processor\Add'
      remove: 'Sitegeist\CriQuel\Processor\Remove'
      unique: 'Sitegeist\CriQuel\Processor\Unique'
      children: 'Sitegeist\CriQuel\Processor\Children'
      tethered: 'Sitegeist\CriQuel\Processor\Tethered'
      filter: 'Sitegeist\CriQuel\Processor\Filter'
      ancestors: 'Sitegeist\CriQuel\Processor\Ancestors'
      descendants: 'Sitegeist\CriQuel\Processor\Descendants'
      withAncestors: 'Sitegeist\CriQuel\Processor\WithAncestors'
      withDescendants: 'Sitegeist\CriQuel\Processor\WithDescendants'
      referencingNodes:  'Sitegeist\CriQuel\Processor\ReferencingNodes'
      referencedByNodes:  'Sitegeist\CriQuel\Processor\ReferencedByNodes'

      # final Extractor operations
      getNodes: 'Sitegeist\CriQuel\Extractor\GetNodes'
      getNode: 'Sitegeist\CriQuel\Extractor\GetNode'
      getReferences: 'Sitegeist\CriQuel\Extractor\GetReferences'
      getReference: 'Sitegeist\CriQuel\Extractor\GetReference'
      getProperties: 'Sitegeist\CriQuel\Extractor\GetProperties'
      getProperty: 'Sitegeist\CriQuel\Extractor\GetProperty'
      getCount: 'Sitegeist\CriQuel\Extractor\GetCount'
